### ISSUE TITLE
Request:  Ability to customize colors

### ISSUE THREAD

**Issue by kylania** [kandashi/rarity-colors#1]
It would be useful for those who are color blind or using a dark mode sheet to be able to customize colors with this mod.

As seen here, half the colors are difficult to read while either equipped or not on the dark mode sheet:

![Capture](https://user-images.githubusercontent.com/119372/141006418-166d5aca-dbdc-42c3-80f5-a97d04aa4903.JPG)

My color blind friend also wanted to include:  "please don't use red _and_ green, or blue _and_ purple"

**Comment by samgrieve** [comment]
As a heavily colour blind user I also massively appreciate anything that allows me to customise the colours. Would love this.

**Comment by Vesselchuck** [comment]
I also support this suggestion, as this module is very promising, but for a slightly different reason. The inability to change colours brings some difficulties. In my games, I use predefined background colours and a template from Lineage II, depending on the rarity of the item for the icons. If the item names could also be coloured in a specified colour for when I was using the standard Foundry VTT icon, or match the background, it would be great.

**Comment by kandashi** [comment]
Fixed in latest release
