### ISSUE TITLE
Pathfinder 2E not Supported

### ISSUE THREAD

**Issue by Armandeus66** [kandashi/rarity-colors#4]
Foundry Hub lists this as for "all systems."
However, in Pathfinder 2E, only feats and spells are colored, and only in one color, not by rarity. Items and monsters are not colored. It doesn't seem that Pathfinder 2E is supported.
If possible, please support PF2E as well as D&D5E. For spells, feats, items, and monsters, we would need these rarities: uncommon, common, rare, unique.
Thanks.

**Comment by kandashi** [comment]
When creating the system I specifically enquired about pf2 and was told that rarity mattered little in the system, and that item level mattered much more. I cannot dedicate much time to adding new features to niche modules at the moment
